backend:
  name: git-gateway
  use_large_media_transforms_in_media_library: false

media_folder: 'assets/uploads/pages'

logo_url: 'https://d33wubrfki0l68.cloudfront.net/f1afd154dd1bd09e6957dce7291bfc56834b4489/b2edb/assets/img/brand/logo.svg'

collections:
  - label: "Paginas"
    name: "pages"
    folder: "_pages"
    create: true
    fields:
      - {label: "Titulo da Pagina", name: "title", widget: "string"}
      - {label: "Background da Pagina", name: "image-cover", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}